version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: missive-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: missive
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - missive_pgdata:/var/lib/postgresql/data
      - ./.docker/init:/docker-entrypoint-initdb.d

volumes:
  missive_pgdata:
