import { z } from "zod";

// ──────────────────────────────────────────────
// Missive — A communication artifact
// ──────────────────────────────────────────────

export const MissiveChannel = z.enum([
  "email",
  "chat",
  "ticket",
  "comment",
  "sms",
  "notification",
  "social",
]);
export type MissiveChannel = z.infer<typeof MissiveChannel>;

export const MissiveDirection = z.enum(["inbound", "outbound"]);
export type MissiveDirection = z.infer<typeof MissiveDirection>;

export const ConnectorProvider = z.enum([
  "gmail",
  "outlook",
  "slack",
  "discord",
  "facebook",
  "whatsapp",
  "crm",
  "helpdesk",
  "imap",
]);
export type ConnectorProvider = z.infer<typeof ConnectorProvider>;

export const MissiveStatus = z.enum([
  "unread",
  "read",
  "archived",
  "deleted",
]);
export type MissiveStatus = z.infer<typeof MissiveStatus>;

export const MissiveSchema = z.object({
  id: z.string().ulid(),
  threadId: z.string().ulid(),
  channel: MissiveChannel,
  direction: MissiveDirection,
  provider: ConnectorProvider,
  providerMessageId: z.string(),
  subject: z.string().optional(),
  body: z.string(),
  bodyHtml: z.string().optional(),
  summary: z.string().optional(),
  from: z.object({
    name: z.string().optional(),
    address: z.string(),
  }),
  to: z.array(
    z.object({
      name: z.string().optional(),
      address: z.string(),
    })
  ),
  cc: z
    .array(
      z.object({
        name: z.string().optional(),
        address: z.string(),
      })
    )
    .optional(),
  bcc: z
    .array(
      z.object({
        name: z.string().optional(),
        address: z.string(),
      })
    )
    .optional(),
  attachments: z
    .array(
      z.object({
        id: z.string().ulid(),
        filename: z.string(),
        mimeType: z.string(),
        size: z.number(),
        storagePath: z.string().optional(),
      })
    )
    .optional(),
  headers: z.record(z.string()).optional(),
  status: MissiveStatus,
  classification: z.string().optional(),
  folder: z.string().optional(),                   // folder slug (inbox, archived, invoices, complaints, or custom)
  accountEmail: z.string().optional(),            // which account this was synced from (e.g. user@gmail.com)
  entityIds: z.array(z.string()).optional(),     // denormalized refs to Pathway entity IDs
  organizations: z.array(z.string()).optional(), // organization names this missive belongs to
  projects: z.array(z.string()).optional(), // project names this missive belongs to
  receivedAt: z.string().datetime(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type Missive = z.infer<typeof MissiveSchema>;

// ──────────────────────────────────────────────
// Thread — A collection of related Missives
// ──────────────────────────────────────────────

export const ThreadSchema = z.object({
  id: z.string().ulid(),
  provider: ConnectorProvider,
  providerThreadId: z.string(),
  subject: z.string().optional(),
  participants: z.array(
    z.object({
      name: z.string().optional(),
      address: z.string(),
    })
  ),
  messageCount: z.number(),
  missiveIds: z.array(z.string().ulid()),
  entityIds: z.array(z.string()).optional(),     // denormalized refs to Pathway entity IDs
  summary: z.string().optional(),                // generated by Missive AI
  lastActivityAt: z.string().datetime(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type Thread = z.infer<typeof ThreadSchema>;

// ──────────────────────────────────────────────
// Entity reference — lightweight, used for display
// Missive stores entityIds as denormalized refs.
// Full entity data, relationships, and graph owned by Pathway.
// ──────────────────────────────────────────────

export const EntityReferenceSchema = z.object({
  id: z.string(),
  type: z.enum(["person", "company", "project", "product", "document", "opportunity", "account"]),
  name: z.string(),
});
export type EntityReference = z.infer<typeof EntityReferenceSchema>;

// ──────────────────────────────────────────────
// Folder — organizes missives
// ──────────────────────────────────────────────

export const FolderSchema = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  icon: z.string().optional(),
  color: z.string().optional(),
  system: z.boolean(), // true = auto-created (inbox, archived, invoices, etc.)
  order: z.number(),
  missiveCount: z.number().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type Folder = z.infer<typeof FolderSchema>;

export const SYSTEM_FOLDERS = [
  { name: "Inbox", slug: "inbox", icon: "inbox", system: true, order: 0 },
  { name: "Archived", slug: "archived", icon: "archive", system: true, order: 1 },
  { name: "Invoices", slug: "invoices", icon: "file-text", system: true, order: 2 },
  { name: "Complaints", slug: "complaints", icon: "alert-triangle", system: true, order: 3 },
  { name: "Leads", slug: "leads", icon: "user-plus", system: true, order: 4 },
  { name: "Support", slug: "support", icon: "life-buoy", system: true, order: 5 },
  { name: "Personal", slug: "personal", icon: "user", system: true, order: 6 },
] as const;

// ──────────────────────────────────────────────
// Rule — AI-generated organization rules with user approval
// ──────────────────────────────────────────────

/** Conditions that can be checked against a missive */
export const RuleConditionSchema = z.object({
  field: z.enum([
    "from_address",       // sender email matches
    "from_domain",        // sender domain matches
    "subject_contains",   // subject includes text
    "subject_matches",    // subject regex
    "body_contains",      // body includes text
    "has_attachments",    // boolean
    "channel",            // email, chat, etc.
    "classification",     // invoice, lead, etc.
    "account_email",      // which account received it
    "received_after",     // time-based
    "received_before",
    "direction",          // inbound / outbound
  ]),
  operator: z.enum(["equals", "not_equals", "contains", "not_contains", "matches", "before", "after"]),
  value: z.string(),
});
export type RuleCondition = z.infer<typeof RuleConditionSchema>;

/** Actions to take when a rule matches */
export const RuleActionSchema = z.object({
  type: z.enum([
    "move_to_folder",     // move to a folder
    "mark_read",          // mark as read
    "mark_unread",        // mark as unread
    "archive",            // archive (move to archived folder)
    "label",              // add a classification label
    "delete",             // send to trash
    "forward",            // forward to email (future)
    "notify",             // send a notification
  ]),
  // Extra params depend on type:
  // move_to_folder → params: { folder: "invoices" }
  // label → params: { label: "important" }
  params: z.record(z.string()).optional(),
});
export type RuleAction = z.infer<typeof RuleActionSchema>;

export const RuleSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string().optional(),      // human-readable explanation
  enabled: z.boolean(),
  conditions: z.array(RuleConditionSchema),
  // AND logic: all conditions must match for the rule to fire
  actions: z.array(RuleActionSchema),
  // All actions run in sequence
  priority: z.number().optional(),         // higher = evaluated first
  appliedCount: z.number().optional(),     // how many times it matched
  lastAppliedAt: z.string().datetime().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type Rule = z.infer<typeof RuleSchema>;

/** A rule proposal returned by the AI before user approval */
export const RuleProposalSchema = z.object({
  name: z.string(),
  description: z.string(),
  conditions: z.array(RuleConditionSchema),
  actions: z.array(RuleActionSchema),
  clarification: z.string().optional(),    // if the AI needs to ask something
  needsClarification: z.boolean(),         // true = need more info from user
});
export type RuleProposal = z.infer<typeof RuleProposalSchema>;

// ──────────────────────────────────────────────
// Connector — Source system configuration
// ──────────────────────────────────────────────

export const ConnectorConfigSchema = z.object({
  id: z.string().ulid(),
  provider: ConnectorProvider,
  label: z.string(),
  enabled: z.boolean(),
  credentials: z.record(z.unknown()),
  settings: z.record(z.unknown()).optional(),
  lastSyncAt: z.string().datetime().optional(),
  status: z.enum(["active", "error", "disconnected"]),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type ConnectorConfig = z.infer<typeof ConnectorConfigSchema>;